#!/bin/bash

#
# Usage:
#  ./collector [output file]
#
# Output will be of the format:
# [device name] [SMART overall status] [raw read error rt] [reallocated sector ct] [reallocated event ct] [current pending] [offline uncorrectable] [udma crc error ct]
#

# Check command line arguments
if [ -z "$1" ]; then
        echo "Usage: $0 [output file]"
        exit
fi

outfile=$1

# Get the number of output fields in lsscsi output on this system (it can vary)
# We will use this later to filter out the device names from lsscsi output (always the last field in a line)
field_ct=`/usr/bin/lsscsi | /bin/grep /dev/ | /bin/grep -Ev 'PERC|Dell|DELL|HP|DVD|enclosu' | /usr/bin/tr -s ' ' | /usr/bin/head -1 | /usr/bin/awk -F ' ' '{print NF; exit}'`

# Gather data from each drive
for drive in `/usr/bin/lsscsi | /bin/grep /dev/ | /bin/grep -Ev 'PERC|Dell|DELL|HP|DVD|enclosu' | /usr/bin/tr -s ' ' | /usr/bin/cut -f $field_ct -d ' '` ; do
    # Catch the special case of a machine using partitions instead of whole disks for RAID members
    if /sbin/fdisk -l $drive | grep raid > /dev/null 2>&1; then
        device=`fdisk -l $drive | grep raid | tr -s ' ' | cut -d ' ' -f 1`
    else
        device=$drive
    fi
    
    # Member of md array
    if /sbin/mdadm --examine $device > /dev/null 2>&1; then
        { echo $device | /usr/bin/tr '\n' ' ';
        /sbin/mdadm --examine $device | /bin/grep Name | /usr/bin/awk '{$1=$1};1' | /usr/bin/cut -d ' ' -f 3 | /usr/bin/cut -d ':' -f 2 | /bin/sed -e 's/^/\/dev\/md/' | /usr/bin/tr '\n' ' ';
        /usr/sbin/smartctl -H $device | /bin/grep overall-health | /usr/bin/cut -d ' ' -f 6 | /usr/bin/tr '\n' ' ';
        /usr/sbin/smartctl -A $device | /bin/grep '^  1\|^  5\|^196\|^197\|^198\|^199' | /usr/bin/tr -s ' ' | /usr/bin/awk '{$1=$1};1' | /usr/bin/cut -d ' ' -f 10 | /usr/bin/tr '\n' ' ';
        echo; } | /bin/cat >> $outfile
    # Not member of md array
    else
        { echo $device | /usr/bin/tr '\n' ' ';
        echo "NONE" | /usr/bin/tr '\n' ' ';
        /usr/sbin/smartctl -H $device | /bin/grep overall-health | /usr/bin/cut -d ' ' -f 6 | /usr/bin/tr '\n' ' ';
        /usr/sbin/smartctl -A $device | /bin/grep '^  1\|^  5\|^196\|^197\|^198\|^199' | /usr/bin/tr -s ' ' | /usr/bin/awk '{$1=$1};1' | /usr/bin/cut -d ' ' -f 10 | /usr/bin/tr '\n' ' ';
        echo; } | /bin/cat >> $outfile
    fi
done
